apiVersion: v1
kind: Pod
metadata:
  name: awspd
spec:
  containers:
    - name: myfrontend
      image: aosqe/hello-openshift
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - name: ebs
          mountPath: "/mnt/aws"
  volumes:
    - name: ebs
      awsElasticBlockStore:
        volumeID: aws://us-east-1c/vol-943fcc74
        fsType: ext4
