kind: PersistentVolume
apiVersion: v1
metadata:
  name: ebsinvalid
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: "vol-00000123"
    fsType: "ext4"
