kind: PersistentVolume
apiVersion: v1
metadata:
  name: ebs
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: "aws://us-east-1d/vol-e69f0b1c"
    fsType: "ext4"
