apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  containers:
  - image: gcr.io/google_containers/test-webserver
    name: pod
    volumeMounts:
    - mountPath: /test-pd
      name: vol
  volumes:
  - name: vol
    scaleIO:
      gateway: https://localhost:443/api
      system: scaleio
      volumeName: vol
      secretRef:
        name: sio-secret
      fsType: xfs
