apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-terminating
spec:
  hard:
    pods: "4"
    requests.cpu: 1000m
    requests.memory: 1Gi    
    limits.cpu: 2000m
    limits.memory: 2Gi    
  scopes:
   - Terminating
