apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: glusterprovisioner
provisioner: kubernetes.io/glusterfs
parameters:
  endpoint: "glusterfs-cluster"
  resturl: "http://ec2-52-91-208-229.compute-1.amazonaws.com:9991"
  restuser: "admin"
  restuserkey: "test"
