apiVersion: extensions/v1beta1
kind: StorageClass
metadata:
  name: fast
provisioner: kubernetes.io/glusterfs
parameters:
  endpoint: "glusterfs-cluster"
  resturl: "http://172.18.4.122:9991"
  restauthenabled: "false"
  restuser: "admin"
  restuserkey: "password"
