apiVersion: v1
kind: Pod
metadata:
  name: pod-limit-memory
  labels:
    name: pod-limit-memory
spec:
  containers:
  - name: pod-limit-memory
    image: openshift/mysql-55-centos7:latest
    env:
    - name: MYSQL_USER
      value: userSUM
      name: MYSQL_PASSWORD
      value: P5J6s8wf
      name: MYSQL_DATABASE
      value: root
      name: MYSQL_ROOT_PASSWORD
      value: W5J6s8wf
    resources:
      limits:
        memory: "300Mi"
    volumeMounts:
    - mountPath: /var/lib/mysql/data
      name: tmp
  volumes:
  - emptyDir: {}
    name: tmp

