kind: Pod
apiVersion: v1
metadata:
  name: mypod
spec:
  containers:
    - name: mycontainer
      image: aosqe/storage
      ports:
        - containerPort: 80
          name: "http-server"
      volumeDevices:
      - devicePath: /dev/xvda
        name: myvolume
  volumes:
    - name: myvolume
      persistentVolumeClaim:
        claimName: mypvc
