apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: sriov-network
  annotations:
    k8s.v1.cni.cncf.io/resourceName: intel.com/sriov
spec:
  config: '{
        "type": "sriov",
        "name": "sriov-network",
        "if0": "eno1",
        "ipam": {
                "type": "host-local",
                "subnet": "10.11.11.0/24",
                "routes": [{
                        "dst": "0.0.0.0/0"
                }],
                "gateway": "10.11.11.1"
        }
}'
