apiVersion: v1
kind: Pod
metadata:
  generateName: testpod-
  annotations:
    k8s.v1.cni.cncf.io/networks: sriov-network
spec:
  containers:
  - name: test-pod
    image: bmeng/centos-network
    resources:
      requests:
        openshift.io/sriov: 1
      limits:
        openshift.io/sriov: 1
