apiVersion: v1
kind: ClusterRole
metadata:
  name: clusterservicebroker-admin
rules:
- apiGroups:
  - servicecatalog.k8s.io
  attributeRestrictions: null
  resources:
  - clusterservicebrokers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
