apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: ups-instance-1
  namespace: test-ns
spec:
  clusterServiceClassExternalName: user-provided-service
  clusterServicePlanExternalName: default
