apiVersion: v1
kind: Template
metadata:
  name: ups-binding
objects:
- apiVersion: servicecatalog.k8s.io/v1beta1
  kind: ServiceBinding
  metadata:
    name: ${BINDING_NAME}
    namespace: ${USER_PROJECT}
  spec:
    instanceRef:
      name: ${INSTANCE_NAME}
    secretName: ${SECRET_NAME}
    secretTransforms:
    - renameKey:
        from: ${OLD_KEY_1}
        to: ${NEW_KEY_1}       
    - renameKey:
        from: ${OLD_KEY_2}
        to: ${NEW_KEY_2}      

parameters:
- description: Binding name
  displayname: Binding name
  name: BINDING_NAME
  value: ups-binding

- description: User project
  displayname: User project
  name: USER_PROJECT
  value: test-ns

- description: Instance name
  displayname: Instance name
  name: INSTANCE_NAME
  value: ups-instance

- description: Secret name
  displayname: Secret name
  name: SECRET_NAME
  value: ups-secret

- description: Old key-1 name
  displayname: Old key-1 name
  name: OLD_KEY_1
  value: special-key-1

- description: Old key-2 name
  displayname: Old key-2 name
  name: OLD_KEY_2
  value: special-key-2

- description: New key-1 name
  displayname: New key-1 name
  name: NEW_KEY_1
  value: test-key-1

- description: New key-2 name
  displayname: New key-2 name
  name: NEW_KEY_2
  value: test-key-2
