apiVersion: v1
kind: Service
metadata:
  labels:
    app: ups-broker
    chart: ups-broker-0.0.1
    heritage: Tiller
    release: ups-broker
  name: ups-broker
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: ups-broker
  sessionAffinity: None
  type: ClusterIP