apiVersion: v1
kind: Pod
metadata:
  name: empty-operator-pod
spec:
  containers:
    - image: "docker.io/ocpqe/hello-pod"
      name: hello-pod
  nodeSelector:
    vip: vip1
  tolerations:
    - key: dedicated
      value: special-user
      effect: NoSchedule
