apiVersion: v1
kind: Pod
metadata:
  labels:
    name: hello-pod-conflict
  name: hello-pod-conflict
spec:
  containers:
    - image: "docker.io/deshuai/hello-pod:latest"
      imagePullPolicy: IfNotPresent
      name: hello-pod
      ports:
        - containerPort: 8080
          protocol: TCP
      resources: {}
      securityContext:
        capabilities: {}
        privileged: false
      terminationMessagePath: /dev/termination-log
      volumeMounts:
        - mountPath: /tmp
          name: tmp
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  serviceAccount: ""
  tolerations:
  - key: key1
    value: value2
  volumes:
    - emptyDir: {}
      name: tmp
