apiVersion: v1
kind: Pod
metadata:
  name: node-affinity-preferred-case14509
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
          - key: case14509
            operator: In
            values:
            - case14509
  containers:
  - name: rhel7
    image: registry.access.redhat.com/openshift3/container-engine
