apiVersion: v1
kind: Pod
metadata:
  name: node-anti-affinity-required-case14484
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: key14484
            operator: NotIn
            values:
            - value14484
  containers:
  - name: rhel7
    image: registry.access.redhat.com/openshift3/container-engine
