apiVersion: v1
kind: Pod
metadata:
  name: node-affinity-required-us
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: zone
            operator: In
            values:
            - us
  containers:
  - image: registry.access.redhat.com/openshift3/container-engine
    name: rhel7
