apiVersion: v1
kind: Pod
metadata:
  name: node-affinity-required-case14478
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: key14478
            operator: In
            values:
            - value14478
  containers:
  - name: rhel7
    image: registry.access.redhat.com/openshift3/container-engine
