apiVersion: v1
kind: Pod
metadata:
  name: node-affinity-required-exists-case14520
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: case14520
            operator: Exists
  containers:
  - name: rhel7
    image: registry.access.redhat.com/openshift3/container-engine
