apiVersion: v1
kind: Pod
metadata:
  name: node-anti-affinity-preferred
spec:
  containers:
    - image: "docker.io/ocpqe/hello-pod"
      name: hello-pod
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 99
        preference:
          matchExpressions:
          - key: "beta.kubernetes.io/arch"
            operator: NotIn
            values:
            - amd64
