apiVersion: v1
kind: Pod
metadata:
  name: node-affinity-gt4-required-case14522
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: key14522
            operator: Gt
            values:
            - "4"
  containers:
  - name: rhel7
    image: registry.access.redhat.com/openshift3/container-engine
