apiVersion: v1
kind: Pod
metadata:
  name: node-affinity-required-case14479
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: key14479
            operator: In
            values:
            - value14479
  containers:
  - name: rhel7
    image: registry.access.redhat.com/openshift3/container-engine
