apiVersion: v1
kind: Pod
metadata:
  name: multiple-match-expressions-case14577
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: key14577
            operator: In
            values:
            - value14577
          - key: company14577
            operator: In
            values:
            - redhat
  containers:
  - name: rhel7
    image: registry.access.redhat.com/openshift3/container-engine
