apiVersion: v1
kind: Pod
metadata:
  name: node-affinity-selector-case14557
spec:
  nodeSelector:
    case14557: case14557
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: zone14557
              operator: In
              values:
              - case14557
  containers:
  - image: registry.access.redhat.com/openshift3/container-engine
    name: rhel7
