apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    run: hello-openshift
  name: hello-openshift
spec:
  replicas: 1
  selector:
    run: hello-openshift
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: hello-openshift
    spec:
      nodeName: thehostnameofanode
      containers:
      - image: openshift/hello-openshift
        imagePullPolicy: Always
        name: hello-openshift
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
