apiVersion: v1
kind: LimitRange
metadata:
  name: limits
  namespace: proj1
spec:
  limits:
  - type: Container
    max:
      cpu: 200m
      memory: 1Gi
    defaultRequest:
      cpu: 400m
      memory: 2Gi
