apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/display-name: This is test is myhttpd (httpd)
  generation: 1
  name: myhttpd
  namespace: openshift
  selfLink: /apis/image.openshift.io/v1/namespaces/openshift/imagestreams/httpd
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      description: Build and serve static content via Apache HTTP Server (httpd) 2.4
        on RHEL 7. For more information about using this builder image, including
        OpenShift considerations, see https://github.com/sclorg/httpd-container/blob/master/2.4/README.md.
      iconClass: icon-apache
      openshift.io/display-name: Apache HTTP Server 2.4
      openshift.io/provider-display-name: Red Hat, Inc.
      sampleRepo: https://github.com/sclorg/httpd-ex.git
      supports: httpd
      tags: builder,httpd, mycat
      version: "2.4"
    from:
      kind: DockerImage
      name: registry.access.redhat.com/rhscl/httpd-24-rhel7
    generation: 2
    importPolicy: {}
    name: "2.4"
    referencePolicy:
      type: Source

