kind: Pod
apiVersion: v1
metadata:
  name: pod-1
spec:
  containers:
    - name: myfront
      image: aosqe/prom2json
      imagePullPolicy: IfNotPresent
      command: ["sh", "-c", "while true; do sleep 10; done"]
      volumeMounts:
      - mountPath: "/cert"
        name: kubelet-cert
        readOnly: true
      - mountPath: "/key"
        name: kubelet-key
        readOnly: true
  volumes:
    - name: kubelet-cert
      secret:
        defaultMode: 0666
        secretName: kubelet-cert
    - name: kubelet-key
      secret:
        defaultMode: 0666
        secretName: kubelet-key
