apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    run: sj3
  name: sj3
spec:
  concurrencyPolicy: Allow
  jobTemplate:
    metadata:
      name: sj3
    spec:
      completion: 5
      Parallelism: 1
      activeDeadlineSeconds: 300
      template:
        metadata:
          labels:
            run: sj3
        spec:
          containers:
          - args:
            - sleep
            - "10"
            image: busybox
            imagePullPolicy: Always
            name: sj3
            resources: {}
          restartPolicy: Never
  schedule: '*/1 * * * *'
  suspend: false
  startingDeadlineSeconds: 300
