apiVersion: batch/v1
kind: Job
metadata:
  name: zero
spec:
  manualSelector: true
  selector:         
    matchLabels:
      app: pi
  parallelism: 1    
  completions: 1
  activeDeadlineSeconds: 0
  template:         
    metadata:
      name: pi
      labels:
        app: pi
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
