apiVersion: v1
kind: Pod
metadata:
  generateName: macvlan-dhcp-pod-
  annotations:
    k8s.v1.cni.cncf.io/networks: macvlan-dhcp
spec:
  containers:
  - name: macvlan-dhcp-pod
    image: docker.io/bmeng/centos-network
