apiVersion: v1
kind: Pod
metadata:
  name: multus-default-route-pod
  annotations:
    k8s.v1.cni.cncf.io/networks: '[{
      "name": "macvlan-conf",
      "default-route": ["192.168.2.2"]
    }]'
spec:
  containers:
  - name: multus-default-route-pod
    command: ["/bin/bash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: dougbtv/centos-network
EOF
