apiVersion: v1
kind: Pod
metadata:
  name: multus-default-route-pod
  annotations:
    k8s.v1.cni.cncf.io/networks: '[{
      "name": "bridge-static",
      "default-route": ["22.2.2.254"]
    }]'
spec:
  containers:
  - name: multus-default-route-pod
    command: ["/bin/bash", "-c", "sleep 2000000000000"]
    image: dougbtv/centos-network
