apiVersion: v1
kind: Pod
metadata:
  name:  runtimeconfig-pod
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
      {
        "name": "runtimeconfig-def",
        "ips": [ "192.168.22.2/24" ],
        "mac": "CA:FE:C0:FF:EE:00"
      }
    ]'
spec:
  containers:
  - name:  runtimeconfig-pod
    command: ["/bin/bash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: dougbtv/centos-network
