apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: cephfs
provisioner: ceph.com/cephfs
parameters:
  monitors: "xxx:6789"
  adminId: "admin"
  adminSecretName: "cephrbd-secret"
  adminSecretNamespace: "default"
