apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    name: mypod
spec:
  containers:
  - name: mypod
    image: nginx
    resources:
      limits:
        cpu: 1500m
        memory: 600Mi
      requests:
        cpu: 100m
        memory: 400Mi
