apiVersion: v1
kind: Pod
metadata:
  name: hello-openshift-invalid
  labels:
    role: hello-openshift-invalid
spec:
  containers:
    - name: hello-openshift-invalid
      image: aosqe/hello-openshift
      ports:
        - name: nfs
          containerPort: 2049
      securityContext:
        privileged: false
  securityContext:
    supplementalGroups:
      - -1234
      - -5678
