apiVersion: v1
kind: Pod
metadata:
  name: multi-containers
  labels:
    role: multi-containers
spec:
  containers:
    - name: hello-openshift
      image: aosqe/hello-openshift
      ports:
        - name: nfs
          containerPort: 8080
      securityContext:
        privileged: false
    - name: nfs-server
      image: aosqe/nfs-server
      ports:
        - name: nfs
          containerPort: 2050
      securityContext:
        privileged: false
  securityContext:
    supplementalGroups:
      - 1234
      - 5678
