apiVersion: v1
kind: Pod
metadata:
  name: hello-openshift
  labels:
    role: hello-openshift
spec:
  containers:
    - name: hello-openshift
      image: aosqe/hello-openshift
      ports:
        - name: nfs
          containerPort: 2049
      securityContext:
        privileged: false
  securityContext:
    supplementalGroups:
      - 1234
      - 5678
