apiVersion: "logging.openshift.io/v1alpha1"
kind: "ClusterLogging"
metadata:
  name: "hostpath"
spec:
  managementState: "Unmanaged"
  logStore:
    type: "elasticsearch"
    elasticsearch:
      nodeCount: 1
      storage:
        HostPath:
          path: /data
          type: Directory
      redundancyPolicy: "SingleRedundancy"
  visualization:
    type: "kibana"
    kibana:
      replicas: 1
  curation:
    type: "curator"
    curator:
      schedule: "*/10 * * * *"
  collection:
    logs:
      type: "fluentd"
      fluentd: {}
