apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: elasticsearch-operator
  namespace: openshift-operators
spec:
  channel: preview
  installPlanApproval: Automatic
  name: elasticsearch-operator
  source: installed-community-openshift-operators
  sourceNamespace: openshift-operators
  startingCSV: elasticsearch-operator.v0.0.1
