apiVersion: metering.openshift.io/v1alpha1
kind: Report
metadata:
  name: namespace-cpu-request-daily
spec:
  query: "namespace-cpu-request"
  reportingStart: "2019-01-01T00:00:00Z"
  schedule:
    period: "daily"
  inputs:
  - name: NamespaceCPURequestReportName
    value: namespace-cpu-request-hourly
  gracePeriod: 1h # delay running 1 hour so that the hourly report has time to run
