apiVersion: v1
kind: Pod
metadata:
  name: no-podpreset
  labels:
    app: website
    role: frontend
  annotations:
    podpreset.admission.kubernetes.io/exclude: "true"
spec:
  containers:
  - name: rhel7
    image: registry.access.redhat.com/openshift3/container-engine
