apiVersion: v1
kind: Pod
metadata:
  name: pod-volume
  labels:
    app: website
    role: frontend
spec:
  containers:
    - name: hello-pod
      image: docker.io/ocpqe/hello-pod
      volumeMounts:
        - mountPath: /cache
          name: cache-volume
  volumes:
    - name: cache-volume
      emptyDir: {}
