apiVersion: v1
kind: Pod
metadata:
  name: allinone-permission-mode
  labels:
    region: one
spec:
  containers:
  - name: allinone-permission-mode
    image: redis
    resources:
      limits:
        cpu: "500m"
        memory: "256Mi"
    volumeMounts:
    - name: all-in-one
      mountPath: "/all-in-one"
      readOnly: true
  volumes:
  - name: all-in-one
    projected:
      defaultMode: 0400
      sources:
      - secret:
          name: test-secret
          items:
            - key: data-1
              path: mysecret/my-username
            - key: data-2
              path: mysecret/my-passwd
      - downwardAPI:
          defaultMode: 0744
          items:
            - path: mydapi/labels
              fieldRef:
                fieldPath: metadata.labels
            - path: mydapi/name
              fieldRef:
                fieldPath: metadata.name
            - path: mydapi/cpu_limit
              resourceFieldRef:
                containerName: allinone-permission-mode
                resource: limits.cpu
                divisor: "1m"
      - configMap:
          name: special-config
          items:
            - key: special.how
              path: myconfigmap/shared-config
              mode: 0777
            - key: special.type
              path: myconfigmap/private-config
              mode: 0700
