apiVersion: v1
kind: Pod
metadata:
  name: podtocomplete
spec:
  containers:
  - name: pi
    image: perl
    command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
    resources:
      requests:
        cpu: 700m
        memory: 1Gi
  restartPolicy: OnFailure
