apiVersion: v1
kind: Pod
metadata:
  name: pod-affinity-proj-case14697
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: security
            operator: In
            values:
            - s1
        namespaces:
        - <%= cb.proj_name %>
        topologyKey: kubernetes.io/hostname
  containers:
  - name: hello-pod
    image: docker.io/ocpqe/hello-pod
