apiVersion: v1
kind: Pod
metadata:
  name: pod-affinity-s1
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: security
            operator: In
            values:
            - s1
        topologyKey: kubernetes.io/hostname
  containers:
  - name: pod-affinity
    image: registry.access.redhat.com/openshift3/container-engine
