apiVersion: v1
kind: Pod
metadata:
  name: pod-affinity-exists
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: security
            operator: Exists
        topologyKey: kubernetes.io/hostname
  containers:
  - name: rhel7
    image: registry.access.redhat.com/openshift3/container-engine
