apiVersion: v1
kind: Pod
metadata:
  name: pod-affinity-multi-matchexpressions
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: security
            operator: In
            values:
            - s1
          - key: company
            operator: In
            values:
            - redhat
        topologyKey: kubernetes.io/hostname
  containers:
  - name: hello-pod
    image: docker.io/ocpqe/hello-pod
