apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: ds-not-tolerate-taint
spec:
  template:
    metadata:
      labels:
        name: ds-not-tolerate-taint
    spec:
      containers:
      - image: docker.io/ocpqe/hello-pod:latest
        imagePullPolicy: Always
        name: registry
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
      serviceAccount: default
      terminationGracePeriodSeconds: 10
      tolerations:
      - key: role
        value: node
        operator: Equal
        effect: NoExecute
