apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp:
  labels:
    run: dctest
  name: dctest
spec:
  replicas: 1
  selector:
    run: dctest
  strategy:
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        run: dctest
    spec:
      containers:
      - image: aosqe/hello-openshift-centos
        imagePullPolicy: IfNotPresent
        name: dctest-1
        ports:
          -
            containerPort: 8080
            protocol: TCP
        resources:
          limits:
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
      - image: aosqe/hello-openshift-fedora
        imagePullPolicy: IfNotPresent
        name: dctest-2
        ports:
          -
            containerPort: 8081
            protocol: TCP
        resources:
          limits:
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
  triggers:
  - type: ConfigChange
status:
