apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ReplicationController
  metadata:
    labels:
      name: hello-pod
    name: hello-pod
  spec:
    replicas: 2
    selector:
      name: hello-pod
    template:
      metadata:
        creationTimestamp: null
        labels:
          name: hello-pod
      spec:
          containers:
          - image: docker.io/deshuai/hello-pod:latest
            imagePullPolicy: Always
            name: hello-pod
            ports:
            - containerPort: 8080
              protocol: tcp
            resources:
              limits:
                cpu: 500m
                memory: 512Mi
              requests:
                cpu: 100m
                memory: 256Mi
            terminationMessagePath: /dev/termination-log
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          securityContext: {}
          terminationGracePeriodSeconds: 30
- apiVersion: v1
  kind: Service
  metadata:
    name: hello-svc
  spec:
    ports:
    - port: 8000
      targetPort: 8080
      protocol: TCP
    selector:
      name: hello-pod
