apiVersion: "operator.openshift.io/v1"
kind: "Network"
metadata:
  name: "cluster"
spec:
  serviceNetwork:
  - "172.30.0.0/16"
  clusterNetwork:
  - cidr: "10.128.0.0/14"
    hostPrefix: 23
  defaultNetwork:
    type: OpenShiftSDN
    openshiftSDNConfig:
      mode: NetworkPolicy
  additionalNetworks:
    - type: Raw
      name: macvlan-conf
      rawCNIConfig: '{
        "cniVersion": "0.3.0",
        "type": "macvlan",
        "name": "macvlan-network",
        "master": "eth0",
        "mode": "bridge",
        "ipam": {
                "type": "host-local",
                "subnet": "192.168.1.0/24",
                "rangeStart": "192.168.1.200",
                "rangeEnd": "192.168.1.216",
                "routes": [{
                        "dst": "0.0.0.0/0"
                }],
                "gateway": "192.168.1.1"
        }
      }'
