apiVersion: v1
kind: Pod
metadata:
  name: configmap
spec:
  containers:
    - name: test-container
      image: aosqe/hello-openshift
      volumeMounts:
      - name: config-volume
        subpath: subpath
        mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: special-config
  restartPolicy: Never
