apiVersion: v1
kind: Pod
metadata:
  name: pod-15732
spec:
  securityContext:
    supplementalGroups:
    - 0
  containers:
  - image: aosqe/hugepage-test:latest
    name: hp
    volumeMounts:
    - mountPath: /hugepages
      name: hugepage
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
        hugepages-2Mi: 20Mi
      limits:
        hugepages-2Mi: 20Mi
  volumes:
  - name: hugepage
    emptyDir:
      medium: HugePages
