apiVersion: v1
kind: Pod
metadata:
  name: pod-notbesteffort
  labels:
    name: pod-notbesteffort
spec:
  containers:
  - name: pod-notbesteffort
    image: openshift/mysql-55-centos7:latest
    env:
    - name: MYSQL_USER
      value: userSUM
      name: MYSQL_PASSWORD
      value: P5J6s8wf
      name: MYSQL_DATABASE
      value: root
      name: MYSQL_ROOT_PASSWORD
      value: W5J6s8wf
    resources:
      limits:
        cpu: "500m"
        memory: "256Mi"
      requests:
        cpu: "200m"
        memory: "256Mi"
