apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Secret
  metadata:
    name: secret-1
  data:
    data-1: dmFsdWUtMQ0K
    data-2: dmFsdWUtMg0KDQo=
- apiVersion: v1
  kind: Secret
  metadata:
    name: secret-2
  data:
    data-1: dmFsdWUtMQ0K
    data-2: dmFsdWUtMg0KDQo=
  #Succeeded pod
- apiVersion: v1
  kind: Pod
  metadata:
    labels:
      name: hello-pod-1
    name: hello-pod-1
  spec:
    containers:
      - image: "docker.io/ocpqe/hello-pod:latest"
        command: ["sh", "-c", "cat /etc/secret-volume/data-1 /etc/secret-volume/data-2;exit 0"]
        imagePullPolicy: IfNotPresent
        name: hello-pod-1
        ports:
          - containerPort: 8080
            protocol: TCP
        resources: {}
        securityContext:
          capabilities: {}
          privileged: false
        terminationMessagePath: /dev/termination-log
        volumeMounts:
          - mountPath: /etc/secret-volume
            name: secret-volume-1
    dnsPolicy: ClusterFirst
    restartPolicy: Never
    serviceAccount: ""
    volumes:
      - secret:
         secretName: secret-1
        name: secret-volume-1
  #Failed pod
- apiVersion: v1
  kind: Pod
  metadata:
    labels:
      name: hello-pod-2
    name: hello-pod-2
  spec:
    containers:
      - image: "docker.io/ocpqe/hello-pod:latest"
        command: ["sh", "-c", "cat /etc/secret-volume/data-1 /etc/secret-volume/data-2;exit 1"]
        imagePullPolicy: IfNotPresent
        name: hello-pod-2
        ports:
          - containerPort: 8080
            protocol: TCP
        resources: {}
        securityContext:
          capabilities: {}
          privileged: false
        terminationMessagePath: /dev/termination-log
        volumeMounts:
          - mountPath: /etc/secret-volume
            name: secret-volume-2
    dnsPolicy: ClusterFirst
    restartPolicy: Never
    serviceAccount: ""
    volumes:
      - secret:
         secretName: secret-2
        name: secret-volume-2
