kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: azpvc
  annotations:        
    volume.beta.kubernetes.io/storage-class: azsc 
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
