apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "rsyslogserver"
  labels:
    provider: openshift
    component: "rsyslog"
    logging-infra: "rsyslog"
  namespace: openshift-logging
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      provider: openshift
      component: "rsyslog"
      logging-infra: "rsyslog"
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        logging-infra: "rsyslog"
        provider: openshift
        component: "rsyslog"
    spec:
      serviceAccount: rsyslogserver
      serviceAccountName: rsyslogserver
      containers:
      - name: "rsyslog"
        image: docker.io/rsyslog/syslog_appliance_alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 514
          name: rsyslog-pod
        securityContext:
          privileged: true
          procMount: Default
        env:
        - name: "TZ"
          value: "UTC"
        - name: "CONTAINER_SILENT"
          value: "on"
        - name: "ENABLE_LOGFILES"
          value: "on"
        - name: "LOGFILES_STORE"
          value: "/home/rsyslog/hosts/%hostname:::secpath-replace%/messages.log"
        - name: "USE_VALGRIND"
          value: "no"
        - name: "RSYSLOG_DEBUG"
          value: "no"
        - name: "RSYSLOG_DEBUGLOG"
          value: "/home/rsyslog/rsyslog-internal-debug.log"
