apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ipam-name
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "ipam-type",
      "master": "ens3",
      "ipam": {
                    "type": "static",
                    "addresses": [
                        {
                          "address": "22.2.2.22/24",
                          "gateway": "22.2.2.1"
                        }
                    ]
          }
    }'
