apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ipam-name
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "ipam-type",
      "master": "ens3",
      "ipam": {
        "type": "host-local",
        "subnet": "22.2.2.0/24",
        "rangeStart": "22.2.2.100",
        "rangeEnd": "22.2.2.200"
      }
    }'
