apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: myipvlan-1
spec:
  config: '{
        "cniVersion": "0.3.1",
	      "name": "myipvlan-1",
	      "type": "ipvlan",
	      "master": "ens5",
	      "ipam": {
		             "type": "host-local",
		             "subnet": "22.2.2.0/24"
	}
}'
