apiVersion: v1
kind: Pod
metadata:
  name: ipvlan-ipam-static-pod
  annotations:
    k8s.v1.cni.cncf.io/networks: ipvlan-ipam-static
spec:
  containers:
  - name: ipvlan-ipam-static-pod
    command: ["/bin/bash", "-c", "sleep 2000000000000"]
    image: dougbtv/centos-network
