apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: runtimeconfig-def-mac
spec: 
  config: '{
            "cniVersion": "0.3.1",
            "plugins": [
                {
                    "type": "macvlan",
                    "capabilities": { "ips": true },
                    "master": "ens3",
                    "mode": "bridge",
                    "ipam": {
                         "type": "static",
                         "addresses": [
                                {
                                     "address": "22.2.2.22/24"
                                }
                           ]
                    }
                }, {
                    "capabilities": { "mac": true },
                    "type": "tuning"
                } ]
        }'
