apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: runtimeconfig-def
spec:
  config: '{
      "cniVersion": "0.3.1",
      "plugins": [{
          "type": "macvlan",
          "capabilities": { "ips": true },
          "master": "ens5",
          "mode": "bridge",
          "ipam": {
            "type": "static"
          }
        }, {
              "type": "tuning",
              "capabilities": { "mac": true }
        }]
    }'
