apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  manualSelector: true
  parallelism: 5
  selector:
    matchLabels:
      app: pi
  template:
    metadata:
      name: pi
      labels:
        app: pi
    spec:
      containers:
      - name: pi
        image: openshift/perl-516-centos7
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
