kind: Pod
apiVersion: v1
metadata:
  name: pod001
spec:
  containers:
    - name: dynamic
      image: aosqe/storage
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
      - mountPath: "/mnt/"
        name: flex
  volumes:
    - name: flex
      persistentVolumeClaim:
        claimName: claim001
