apiVersion: v1
kind: Pod
metadata:
  name: dapi-resources-env-containername-pod
spec:
  containers:
    - name: client-container
      image: gcr.io/google_containers/busybox
      command: [ "/bin/sh", "-c", "env" ]
      resources:
        requests:
          memory: "32Mi"
          cpu: "150m"
        limits:
          memory: "64Mi"
          cpu: "250m"
      env:
        - name: MY_CPU_REQUEST
          valueFrom:
            resourceFieldRef:
              containerName: client-container
              resource: requests.cpu
        - name: MY_CPU_LIMIT
          valueFrom:
            resourceFieldRef:
              containerName: client-container
              resource: limits.cpu
        - name: MY_MEM_REQUEST
          valueFrom:
            resourceFieldRef:
              containerName: client-container
              resource: requests.memory
              divisor: "1Mi"
        - name: MY_MEM_LIMIT
          valueFrom:
            resourceFieldRef:
              containerName: client-container
              resource: limits.memory
  restartPolicy: Never
