kind: Pod
apiVersion: v1 
metadata:
  name: propashare
spec:
  containers:
    - name: unprivile
      image: docker.io/aosqe/hello-openshift
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/mnt/local"
          name: local
          mountPropagation: Bidirectional 
  volumes:
    - name: local
      hostPath:
        path: "/mnt/disk"
