apiVersion: v1
kind: ClusterRole
metadata:
  name: basic-user
  resourceVersion: "19"
rules:
- apiGroups: null
  attributeRestrictions: null
  resourceNames:
  - "~"
  resources:
  - users
  verbs:
  - get
- apiGroups: null
  attributeRestrictions: null
  resources:
  - projectrequests
- apiGroups: null
  attributeRestrictions: null
  resources:
  - clusterroles
  verbs:
  - get
  - list
- apiGroups: null
  attributeRestrictions: null
  resources:
  - projects
  verbs:
  - list
- apiGroups: null
  attributeRestrictions:
    apiVersion: v1
    kind: IsPersonalSubjectAccessReview
  resources:
  - localsubjectaccessreviews
  - subjectaccessreviews
  verbs:
  - create
