apiVersion: v1
kind: Pod
metadata:
  name: pod-request-limit-valid-4
  labels:
    name: pod-request-limit-valid-4
spec:
  containers:
  - name: pod-request-limit-valid-4
    image: gcr.io/google_containers/nginx
    resources:
      requests:
        cpu: "400m"
        memory: 1024Mi
      limits:
        cpu: "500m"
        memory: 2Gi
