apiVersion: v1
kind: LimitRange
metadata:
  name: limits
  namespace: proj1
spec:
  limits:
  - type: Pod
    max:
      cpu: 960m
      memory: 1024Mi
    min:
      cpu: 20m
      memory: 10Mi
  - type: Container
    default:
      cpu: 240m
      memory: 256Mi
    max:
      cpu: 480m
      memory: 512Mi
    min:
      cpu: 10m
      memory: 5Mi
    defaultRequest:
      cpu: 180m
      memory: 128Mi
    maxLimitRequestRatio:
      cpu: "4"
      memory: "4"
