- set_fact:
    update_is_images_url: "registry.ops.openshift.com"
  when: '"Google" in ansible_bios_version'

- set_fact:
    update_is_images_url: "registry.ops.openshift.com"
  when: '"amazon" in ansible_bios_version'

- set_fact:
    update_is_images_url: "brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888"
  when: '"seabios" in ansible_bios_version'

- set_fact:
    update_is_images_url: "virt-openshift-05.lab.eng.nay.redhat.com:5000"
  when: '"lab.eng.nay.redhat.com" in ansible_fqdn'

- set_fact:
    install_type: "container"
    openshift_example_dir: "/etc/origin/examples"
  when: ansible_local.openshift.common.is_containerized |default(True)

- set_fact:
    install_type: "rpm"
    openshift_example_dir: "/usr/share/openshift/examples/"
  when: not ansible_local.openshift.common.is_containerized |default(True)

- set_fact:
    install_type: "atomic"
    openshift_example_dir: "/etc/origin/examples"
  when: '"ostree" in ansible_cmdline.BOOT_IMAGE'
