apiVersion: v1
kind: Pod
metadata:
  name: pod-no-limit-request
  labels:
    name: pod-no-limit-request
spec:
  containers:
  - name: pod-no-limit-request
    image: openshift/mysql-55-centos7:latest
    env:
    - name: MYSQL_USER
      value: userSUM
      name: MYSQL_PASSWORD
      value: P5J6s8wf
      name: MYSQL_DATABASE
      value: root
      name: MYSQL_ROOT_PASSWORD
      value: W5J6s8wf
    resources: {}
    volumeMounts:
    - mountPath: /var/lib/mysql/data
      name: tmp
  volumes:
  - emptyDir: {}
    name: tmp

