apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    run: cluster-capacity
  name: cluster-capacity
spec:
  replicas: 1
  selector:
    run: cluster-capacity
  template:
    metadata:
      labels:
        run: cluster-capacity
    spec:
        containers:
        - name: cluster-capacity
          image: openshift3/ose-cluster-capacity:latest
          volumeMounts:
          - mountPath: /test-pod
            name: test-volume
          env:
          - name: CC_INCLUSTER
            value: "true"
          command:
          - "/bin/sh"
          - "-ec"
          - |
            /bin/cluster-capacity --podspec=/test-pod/pod.yaml --verbose;while true;do sleep 10;done
        serviceAccountName: cluster-capacity-sa
        volumes:
        - name: test-volume
          configMap:
            name: cluster-capacity-configmap
