apiVersion: v1
kind: Pod
metadata:
 name: azrarw
spec:
 containers:
  - image: aosqe/hello-openshift
    name: azure
    volumeMounts:
      - name: azure
        mountPath: /mnt/azure  
 securityContext:
   runAsUser: 1000060001
   fsGroup: 123456
   seLinuxOptions:
     level: "s0:c8,c2"
 volumes:
   - name: azure
     azureFile:
       secretName: azure-secret
       shareName: azftest 
       readOnly: false
