apiVersion: v1
kind: Pod
metadata:
 name: azure
spec:
 containers:
  - image: aosqe/storage
    name: azure
    volumeMounts:
      - name: azure
        mountPath: /mnt/azure
 volumes:
   - name: azure
     azureDisk:
       diskName: test1.vhd 
       diskURI: https://openshiftqestorage.blob.core.windows.net/vhds/test1.vhd 
