apiVersion: v1
kind: Pod
metadata:
 name: azrarw
spec:
 containers:
  - image: docker.io/aosqe/hello-openshift
    name: azure
    volumeMounts:
      - name: azure
        mountPath: /mnt/azure  
 securityContext:
   runAsUser: 1000060001
   fsGroup: 123456
   seLinuxOptions:
     level: "s0:c8,c2"
 volumes:
   - name: azure
     azureDisk:
       diskName: test1.vhd 
       diskURI: https://openshiftqestorage.blob.core.windows.net/vhds/test1.vhd
       cachingMode: ReadWrite
