apiVersion: v1
kind: DeploymentConfig
metadata: 
  labels:
    run: hello-openshift
  name: hello-openshift
spec: 
  replicas: 1
  selector: 
    run: hello-openshift
  strategy:
    type: Recreate
  template: 
    metadata:
      creationTimestamp: null
      labels: 
        run: hello-openshift
    spec: 
      containers:
      - image: aosqe/hello-openshift
        imagePullPolicy: IfNotPresent 
        name: hello-openshift
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: 
        volumeMounts:
        - name: azure
          mountPath: /mnt/azure  
        terminationMessagePath: /dev/termination-log
      volumes:
      - name: azure
        persistentVolumeClaim:
          claimName: azpvc 
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
