apiVersion: v1
kind: Pod
metadata:
  labels:
    name: hello-pod
  name: pod-sec-two-cont
  annotations:
    container.seccomp.security.alpha.kubernetes.io/hello1: localhost/profile1.json
    container.seccomp.security.alpha.kubernetes.io/hello2: unconfined
spec:
  containers:
    - image: "docker.io/ocpqe/hello-pod:latest"
      imagePullPolicy: IfNotPresent
      name: hello1
      env:
        - name: PORT
          value: "8080"
        - name: SECOND_PORT
          value: "8888"
      ports:
        - containerPort: 8080
          protocol: TCP
      resources: {}
      securityContext:
        capabilities: {}
        privileged: false
      terminationMessagePath: /dev/termination-log
      volumeMounts:
        - mountPath: /tmp
          name: tmp
    - image: "docker.io/ocpqe/hello-pod:latest"
      imagePullPolicy: IfNotPresent
      name: hello2
      env:
        - name: PORT
          value: "8081"
        - name: SECOND_PORT
          value: "8082"
      ports:
        - containerPort: 8081
          protocol: TCP
      resources: {}
      securityContext:
        capabilities: {}
        privileged: false
      terminationMessagePath: /dev/termination-log
      volumeMounts:
        - mountPath: /tmp
          name: tmp
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  serviceAccount: ""
  volumes:
    - emptyDir: {}
      name: tmp
status: {}
