apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  labels:
    app: website
    role: frontend
spec:
  containers:
    - name: hello-pod
      image: docker.io/ocpqe/hello-pod
      ports:
        - containerPort: 80
