apiVersion: v1
kind: Pod
metadata:
  labels:
    name: hello-pod
  name: hello-pod
  annotations:
    pod.alpha.kubernetes.io/init-containers: '[
        {
            "name": "sleep",
            "image": "centos:centos7",
            "command": ["/bin/sh", "-c", "while :; do sleep 2; echo hello init container; done"]
        }
    ]'
spec:
  containers:
    - image: "docker.io/deshuai/hello-pod:latest"
      imagePullPolicy: IfNotPresent
      name: hello-pod
      ports:
        - containerPort: 8080
          protocol: TCP
      resources: {}
      securityContext:
        capabilities: {}
        privileged: false
      terminationMessagePath: /dev/termination-log
      volumeMounts:
        - mountPath: /tmp
          name: tmp
  dnsPolicy: ClusterFirst
  serviceAccount: ""
  volumes:
    - emptyDir: {}
      name: tmp
