apiVersion: v1
kind: Pod
metadata:
  name: init-beta
  annotations:
    pod.beta.kubernetes.io/init-containers: '[
        {
            "name": "success",
            "image": "centos:centos7",
            "command": ["/bin/true"]
        }
    ]'
spec:
  containers:
  - image: "docker.io/ocpqe/hello-pod"
    name: hello-pod
