apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole  # or Role
metadata:
  name: crole-18836
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use
  # Optional
  resourceNames:
  - privileged
