apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod-1
spec:
  containers:
    - name: test-container
      image: gcr.io/google_containers/busybox
      command: [ "/bin/sh", "-c", "while true; do /bin/cat /etc/config/special.how; sleep 2; done" ]
      volumeMounts:
      - name: config-volume
        mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: special-config
  restartPolicy: Never

