apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  namespace: openshift-logging
  name: openshift-logging
  labels:
    og_label: openshift-logging
spec:
  targetNamespaces:
  - openshift-logging
