apiVersion: v1
kind: Pod
metadata:
  name: mapping-secret-volume-pod
spec:
  containers:
    - name: mapping-secret-volume-pod
      image: openshift/mysql-55-centos7:latest
      env:
      - name: MYSQL_USER
        value: userSUM
        name: MYSQL_PASSWORD
        value: P5J6s8wf
        name: MYSQL_DATABASE
        value: root
        name: MYSQL_ROOT_PASSWORD
        value: W5J6s8wf
      volumeMounts:
      - name: secret-volume
        mountPath: /etc/secret-volume
  volumes:
    - name: secret-volume
      secret:
        secretName: secret-n
        items:
        - key: username
          path: test-secrets
  restartPolicy: Never
