apiVersion: v1
kind: Pod
metadata:
  name: multiv-secret-pod
spec:
  containers:
    - name: secretvolume-test
      image: gcr.io/google_containers/mounttest:0.7
      args: [ "--file_content=/etc/secret-volume/data-1", "--file_mode=/etc/secret-volume/data-1" ]
      volumeMounts:
      - name: secret-volume
        mountPath: /etc/secret-volume
        readOnly: true
      - name: volume-secret-opt
        mountPath: /opt/qe-secret
        readOnly: true
  volumes:
    - name: secret-volume
      secret:
        secretName: test-secret
    - name: volume-secret-opt
      secret:
        secretName: test-secret
  restartPolicy: Never
